# 导入所需要的包
keras包

In [21]:
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
import tensorflow.keras
from tensorflow.keras.layers import Dense, Input
from tensorflow.keras import Sequential
from tensorflow.keras.losses import MeanSquaredError, BinaryCrossentropy
from tensorflow.keras.activations import sigmoid
# 导入BinaryCrossentropy损失函数
from tensorflow.keras.losses import BinaryCrossentropy
import logging

logging.getLogger("tensorflow").setLevel(logging.ERROR)  # 暂时取消警告

添加训练样本

In [2]:
X_train = np.array([[1.], [2.]], dtype=np.float32)
Y_train = np.array([[300.], [500.]], dtype=np.float32)

定义一个具有一个神经元或单元的层
采用线性回归模型
$$
f_{\mathbf{w},b}(\mathbf{x}) = \mathbf{w}\cdot \mathbf{x} + b
$$

In [3]:
linear_model = tf.keras.layers.Dense(units=1, activation='linear')

输出此处的权重，当然是没有的，因为还没有训练

In [4]:
print(linear_model.get_weights())

[]


In [5]:
a1 = linear_model(X_train[0].reshape(1,1))
print(a1)

tf.Tensor([[0.4627074]], shape=(1, 1), dtype=float32)


权重被初始化为随机小数，偏差默认初始化为零

In [6]:
w, b = linear_model.get_weights()
print(f"w = {w}, b = {b}")

w = [[0.4627074]], b = [0.]


将权重设置为已知值

In [7]:
set_w = np.array([[200.]])
set_b = np.array([100.])
linear_model.set_weights([set_w, set_b])
print(linear_model.get_weights())

[array([[200.]], dtype=float32), array([100.], dtype=float32)]


In [8]:
a1 = linear_model(X_train[0].reshape(1,1))
print(a1)
alin = np.dot(set_w, X_train[0].reshape(1,1)) + set_b
print(alin)

tf.Tensor([[300.]], shape=(1, 1), dtype=float32)
[[300.]]


产生了相同的结果，现在训练模型

In [9]:
prediction_tf = linear_model(X_train)
prediction_np =  np.dot(X_train, set_w) + set_b

使用模型预测得来的权重和截距可以用来预测，也可以直接使用单个神经元来预测

In [10]:
prediction_np, prediction_tf

(array([[300.],
        [500.]]),
 <tf.Tensor: shape=(2, 1), dtype=float32, numpy=
 array([[300.],
        [500.]], dtype=float32)>)

上述各步骤未经拟合，只是参数正好匹配，所以预测结果完全正确

# 具有sigmoid激活函数的神经元
$$
f_{\mathbf{w},b}(\mathbf{x}) = g\left(\mathbf{w}\cdot \mathbf{x} + b\right)\\
g(z) = \frac{1}{1+e^{-z}}
$$

In [11]:
X_train = np.array([0., 1, 2, 3, 4, 5], dtype=np.float32).reshape(-1,1)
Y_train = np.array([0,  0, 0, 1, 1, 1], dtype=np.float32).reshape(-1,1)
pos = Y_train == 1
neg = Y_train == 0
print(X_train[pos])

[3. 4. 5.]


In [12]:
model = Sequential([tf.keras.layers.Dense(units=1, input_dim=1, activation='sigmoid',name='L1')])

使用keras构建深度学习模型，我们会通过model.summary()输出模型各层的参数状况，如下:

In [13]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
L1 (Dense)                   (None, 1)                 2         
Total params: 2
Trainable params: 2
Non-trainable params: 0
_________________________________________________________________


In [14]:
logistic_layer = model.get_layer('L1')
w, b = logistic_layer.get_weights()
print(w,b)
print(w.shape, b.shape)

[[-0.8207963]] [0.]
(1, 1) (1,)


In [22]:
set_w = np.array([[2]])
set_b = np.array([-4.5])
logistic_layer.set_weights([set_w, set_b])
print(logistic_layer.get_weights())
model.compile(loss=BinaryCrossentropy(), optimizer=tf.keras.optimizers.Adam(0.001), metrics=[tf.keras.metrics.BinaryAccuracy()])
model.fit(X_train, Y_train, epochs=10)

[array([[2.]], dtype=float32), array([-4.5], dtype=float32)]
Epoch 1/10
1/1 [==============================] - 0s 391ms/step - loss: 0.1332 - binary_accuracy: 1.0000
Epoch 2/10
1/1 [==============================] - 0s 7ms/step - loss: 0.1331 - binary_accuracy: 1.0000
Epoch 3/10
1/1 [==============================] - 0s 5ms/step - loss: 0.1331 - binary_accuracy: 1.0000
Epoch 4/10
1/1 [==============================] - 0s 6ms/step - loss: 0.1330 - binary_accuracy: 1.0000
Epoch 5/10
1/1 [==============================] - 0s 5ms/step - loss: 0.1330 - binary_accuracy: 1.0000
Epoch 6/10
1/1 [==============================] - 0s 5ms/step - loss: 0.1329 - binary_accuracy: 1.0000
Epoch 7/10
1/1 [==============================] - 0s 6ms/step - loss: 0.1328 - binary_accuracy: 1.0000
Epoch 8/10
1/1 [==============================] - 0s 6ms/step - loss: 0.1328 - binary_accuracy: 1.0000
Epoch 9/10
1/1 [==============================] - 0s 5ms/step - loss: 0.1327 - binary_accuracy: 1.0000
Epoch 10/1

In [23]:
logistic_layer.get_weights()

[array([[1.9901135]], dtype=float32), array([-4.5099773], dtype=float32)]

In [24]:
a1 = model.predict(X_train[0].reshape(1,1))
print(a1)
alog = sigmoid(np.dot(set_w, X_train[0].reshape(1,1)) + set_b)
print(alog)

[[0.01087905]]
tf.Tensor([[0.01098694]], shape=(1, 1), dtype=float64)
