In [ ]:
import tensorflow as tf
import numpy as np

In [11]:
arr_list = np.arange(1, 100)

In [12]:
dataSet = tf.data.Dataset.from_tensor_slices(arr_list)
dataSet_iterator = dataSet.shuffle(arr_list.shape[0]).batch(10)

In [15]:
def model(xs):
    outputs = tf.multiply(xs, 1)
    return outputs

In [16]:
for it in dataSet_iterator:
    logit = model(it)
    print(logit)

tf.Tensor([33 10 34 68 62 99 22 67  1 96], shape=(10,), dtype=int32)
tf.Tensor([41 66  6 63 15 46 20 19 25 28], shape=(10,), dtype=int32)
tf.Tensor([47 82 36 72 79  2  3 49  5 61], shape=(10,), dtype=int32)
tf.Tensor([57  9 60 89 24 11 90 98 86 54], shape=(10,), dtype=int32)
tf.Tensor([59 52 39 70 87 27 45 23 91 21], shape=(10,), dtype=int32)
tf.Tensor([14 37 93 65 77 95 42 97 44  4], shape=(10,), dtype=int32)
tf.Tensor([ 8 38 12 83 81 84 31 55 40 16], shape=(10,), dtype=int32)
tf.Tensor([74 69 78 18 71 92 48 51 43 32], shape=(10,), dtype=int32)
tf.Tensor([30 80 56 17 64 50 88 85 26 73], shape=(10,), dtype=int32)
tf.Tensor([75 35 94 13 29 76  7 58 53], shape=(9,), dtype=int32)
