# 导入所需要的包
keras包

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow.keras.layers import Dense, Input
from tensorflow.keras import Sequential
from tensorflow.keras.losses import MeanSquaredError, BinaryCrossentropy
from tensorflow.keras.activations import sigmoid
import logging

logging.getLogger("tensorflow").setLevel(logging.ERROR)  # 暂时取消警告

添加训练样本

In [2]:
X_train = np.array([[1.], [2.]], dtype=np.float32)
Y_train = np.array([[300.], [500.]], dtype=np.float32)

定义一个具有一个神经元或单元的层
采用线性回归模型
$$
f_{\mathbf{w},b}(\mathbf{x}) = \mathbf{w}\cdot \mathbf{x} + b
$$

In [3]:
linear_model = tf.keras.layers.Dense(units=1, activation='linear')

输出此处的权重，当然是没有的，因为还没有训练

In [6]:
print(linear_model.get_weights())

[]


In [8]:
a1 = linear_model(X_train[0].reshape(1,1))
print(a1)

tf.Tensor([[0.3991362]], shape=(1, 1), dtype=float32)


权重被初始化为随机小数，偏差默认初始化为零

In [9]:
w, b = linear_model.get_weights()
print(f"w = {w}, b = {b}")

w = [[0.3991362]], b = [0.]


将权重设置为已知值

In [10]:
set_w = np.array([[200.]])
set_b = np.array([100.])
linear_model.set_weights([set_w, set_b])
print(linear_model.get_weights())

[array([[200.]], dtype=float32), array([100.], dtype=float32)]


In [13]:
a1 = linear_model(X_train[0].reshape(1,1))
print(a1)
alin = np.dot(set_w, X_train[0].reshape(1,1)) + set_b
print(alin)

tf.Tensor([[300.]], shape=(1, 1), dtype=float32)
[[300.]]


产生了相同的结果，现在训练模型

In [14]:
prediction_tf = linear_model(X_train)
prediction_np =  np.dot(X_train, set_w) + set_b

In [16]:
prediction_np, prediction_tf

(array([[300.],
        [500.]]),
 <tf.Tensor: shape=(2, 1), dtype=float32, numpy=
 array([[300.],
        [500.]], dtype=float32)>)